### ISSUE TITLE
Typo in FOSS documentation

### ISSUE THREAD

**Issue by ashmichheda** [fossunited/fossunited.org#8]
There is a typo `meeups` instead of `meetups` on the main page of [FOSS](https://fossunited.org/) - under Events

<img width="592" alt="Capture" src="https://user-images.githubusercontent.com/31774401/194737051-21a13796-ffb8-4fe7-b805-e97289773f67.PNG">

**Comment by knadh** [comment]
Fixed. Thanks for reporting.
